
services:
  db:
    image: postgres:15
    container_name: postgres_threatdb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: threatdb
    ports:
       - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    container_name: threat-backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/threatdb
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
    command: npm run dev

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    working_dir: /app
    container_name: threat-frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ../frontend:/app
    command: npm start

volumes:
  postgres_data:
